In [10]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from pycaret.classification import setup, compare_models, create_model, tune_model

In [3]:
import mlflow
import mlflow.sklearn
from urllib.parse import urlparse

In [4]:
df = pd.read_csv("data/intermediate/Telco_post_analysis.csv")

In [5]:
df["Churn"] = LabelEncoder().fit_transform(df["Churn"])
for col in df.drop("customerID",axis=1).columns:
    df[col][(df[col]=="No") | (df[col]=="Male") | (df[col]=="DSL") | (df[col]=="Only Internet")] = 0
    df[col][(df[col]=="Yes") | (df[col]=="Female") | (df[col]=="Fiber optic") | (df[col]=="Phone and Internet")] = 1
    df[col][(df[col]=="No phone service") | (df[col]=="No internet service") | (df[col]=="Only Phone")] = -1
    df[col][df[col] == "Month-to-month"] = 1
    df[col][df[col] == "One year"] = 12
    df[col][df[col] == "Two year"] = 24
    df[col][df[col] == "Mailed check"] = 0
    df[col][df[col] == "Electronic check"] = 1
    df[col][df[col] == "Credit card (automatic)"] = 2
    df[col][df[col] == "Bank transfer (automatic)"] = 3
    df[col] = df[col].astype(float)

In [6]:
my_setup = setup(data = df.drop(["customerID"],axis=1), target="Churn",fold_shuffle=True)

In [7]:
best_model = compare_models()
best_model

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=7895)

In [9]:
gbc = create_model('ada')
gbc

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=7895)